homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret coord_lat
  longitude: !secret coord_long
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 13
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Copenhagen
  # Customization file
  customize: !include customize.yaml
  packages: !include_dir_named packages/

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret http_password
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123
  ip_ban_enabled: True
  login_attempts_threshold: 3
  trusted_networks:
    - 127.0.0.1
    - 192.168.1.0/24

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
recorder:
  purge_interval: 2
  purge_keep_days: 2
  
history: 

logbook:

logger:
  default: warn
  logs:
#    homeassistant.components.switch.broadlink: info
    homeassistant.components.automation: info
    homeassistant.components.script: info
#    homeassistant.components.device_tracker: info
    homeassistant.components.http: debug
#    homeassistant.components.rfxtrx: info
#    homeassistant.components.sensor.miflora: debug
#    homeassistant.components.xiaomi: debug
#    homeassistant.components.sensor.xiaomi: debug
#    homeassistant.components.switch.xiaomi: debug
#    homeassistant.components.binary_sensor: debug
#    custom_components.light.xiaomi: debug
#    miflora.miflora_poller: debug
#    homeassistant.components.sensor.miflora: debug
#    homeassistant.core: info


# Track the sun
sun:

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
