automation:
    - alias: Stefan Seng Dimming
      hide_entity: True
      initial_state: 'on'
      trigger:
        - platform: event
          event_type: click
          event_data:
            entity_id: binary_sensor.switch_158d00016bf42c
            click_type: long_click_press
      condition:
        - condition: state
          entity_id: light.seng_stefan
          state: 'on'
      action:
        - service: script.turn_on
          entity_id: script.dim_light
          data_template:
            variables:
              lyskilde: 'seng_stefan'
              remote: >
                {{ trigger.event.data["entity_id"] }}
          
    - alias: Stefan Seng Dim Toggle
      hide_entity: True
      initial_state: 'on'
      trigger:
        - platform: event
          event_type: click
          event_data:
            entity_id: binary_sensor.switch_158d00016bf42c
            click_type: hold
      condition:
        - condition: state
          entity_id: light.seng_stefan
          state: 'on'
      action:
        - service: input_boolean.toggle
          entity_id: input_boolean.light_dim
          
    - alias: Stefan Seng Light Toggle
      hide_entity: True
      initial_state: 'on'
      trigger:
        - platform: event
          event_type: click
          event_data:
            entity_id: binary_sensor.switch_158d00016bf42c
            click_type: single
      action:
        - service: light.toggle
          entity_id: light.seng_stefan
