homeassistant:
  customize:
    light.gateway_light_286c0785eedc:
      friendly_name: Xiaomi Gateway
    sensor.illumination_286c0785eedc:
      friendly_name: Xiaomi Gateway

###### Cubes ######
    binary_sensor.cube_158d0001148b1d:
      friendly_name: Cube
      hidden: true
      
###### Temp Hum ######
    sensor.humidity_158d00012bdc7a:
      friendly_name: Badeværelse ##Temp1
    sensor.temperature_158d00012bdc7a:
      friendly_name: Badeværelse
      homebridge_hidden: false
    sensor.temperature_158d0001dc1704:
      friendly_name: Emma ##Temp2
      homebridge_hidden: false
    sensor.humidity_158d0001dc1704:
      friendly_name: Emma
    sensor.pressure_158d0001dc1704:
      friendly_name: Emma
      hidden: true
    sensor.temperature_158d0001dc1740:
      friendly_name: Bryggers ##Temp3
      homebridge_hidden: false
    sensor.humidity_158d0001dc1740:
      friendly_name: Bryggers
    sensor.pressure_158d0001dc1740:
      friendly_name: Bryggers
      hidden: true

###### Switches ######
    binary_sensor.switch_158d0001563f14:
      friendly_name: Switch 1
      hidden: true
    binary_sensor.switch_158d00016bf42c:
      friendly_name: Switch 2
      hidden: true
    binary_sensor.switch_158d00018b3e79:
      friendly_name: Switch 3
      hidden: true
      
###### Motionsensor ######
    binary_sensor.motion_sensor_158d000165ffa0:
      friendly_name: Motion 2
    sensor.illumination_158d000165ffa0:
      friendly_name: Motion 2
    binary_sensor.motion_sensor_158d0001a66340:
      friendly_name: Motion 1
    sensor.illumination_158d0001a66340:
      friendly_name: Motion 1
      
###### Door ######
    binary_sensor.door_window_sensor_158d0001d84b39:
      friendly_name: Hoveddør ## Door 1
    binary_sensor.door_window_sensor_158d0001d84ea5:
      friendly_name: Terrassedør ## Door3
    binary_sensor.door_window_sensor_158d0001d86bbb:
      friendly_name: Bryggersdør ## Door 3
      
xiaomi_aqara:
  gateways:
    - mac: 286c0785eedc
      key: !secret xiaomi_key