homeassistant:
  customize:
#### Fibaro Motion 1 ####
    sensor.fibaro_system_fgms001zw5_motion_sensor_general:
      friendly_name: 'Motion 3'
      hidden: true
    sensor.fibaro_system_fgms001zw5_motion_sensor_alarm_type:
      friendly_name: 'Motion 3'
      hidden: true
    sensor.fibaro_system_fgms001zw5_motion_sensor_alarm_level:
      friendly_name: 'Motion 3'
      hidden: true
    sensor.fibaro_system_fgms001zw5_motion_sensor_seismic_intensity:
      friendly_name: 'Motion 3'
      hidden: true
    sensor.fibaro_system_fgms001zw5_motion_sensor_luminance:
      friendly_name: 'Motion 3'
      hidden: true
    sensor.fibaro_system_fgms001zw5_motion_sensor_temperature:
      friendly_name: 'Motion 3'
    binary_sensor.fibaro_system_fgms001zw5_motion_sensor_sensor:
      friendly_name: 'Motion 3'
    

zwave:
  usb_path: /dev/ttyACM1